const rows = [
  {
    id: 1,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '未払い',
  },
  {
    id: 2,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '支払い',
  },
  {
    id: 3,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '未払い',
  },
  {
    id: 4,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '支払い',
  },
  {
    id: 5,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '保留中',
  },
  {
    id: 6,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '保留中',
  },
  {
    id: 7,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '保留中',
  },
  {
    id: 8,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '保留中',
  },
  {
    id: 9,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '保留中',
  },
  {
    id: 10,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '保留中',
  },
  {
    id: 11,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '保留中',
  },
  {
    id: 12,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '保留中',
  },
  {
    id: 13,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '保留中',
  },
  {
    id: 14,
    name: '旋盤のベアリング交換方法',
    duration: '12000',
    viewers: '234',
    revenue: '40000',
    status: '保留中',
  },
];
const slides = [
  {
    image: '/slides/1.png',
    title: '修理動画で学ぼう',
    description:
      '専門家による工作機械や建機、農機の修理動画を視聴・投稿し、知識を共有しながら収益を得られる新しい動画プラットフォームです。',
  },
  {
    image: '/slides/1.png',
    title: '修理動画で学ぼう',
    description:
      '専門家による工作機械や建機、農機の修理動画を視聴・投稿し、知識を共有しながら収益を得られる新しい動画プラットフォームです。',
  },
  {
    image: '/slides/3.png',
    title: '修理動画で学ぼう',
    description:
      '専門家による工作機械や建機、農機の修理動画を視聴・投稿し、知識を共有しながら収益を得られる新しい動画プラットフォームです。',
  },
];
const lastest = {
  icon: '/icons/icons-setting.png',
  title: '最新の動画',
  description:
    'プロフェッショナルが投稿した最新の機械修理動画で、今すぐ新しい修理方法を学びましょう。',
};
const favorite = {
  icon: '/icons/icons-fav.png',
  title: '人気動画',
  description:
    '再生数が多い人気の修理動画を集めました。今すぐチェックして、役立つ修理テクニックを学びましょう！',
};
const news = {
  icon: '/icons/icons-nesw.png',
  title: 'ニュース',
  description:
    '最新のニュースやお知らせをまとめてご確認いただけます。サービスのアップデートや重要な情報をお見逃しなく。',
};
const userIcon = {
  icon: '/icons/icons-nesw.png',
  title: 'トップ貢献者',
  description:
    '多くの動画を投稿し、コミュニティに大きく貢献しているユーザーを紹介します。彼らの豊富な知識と経験を活かした動画は、多くの視聴者に支持されています。',
};
const favVideos = [
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen.png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (1).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (2).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (3).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (4).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (5).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (1).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (2).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (3).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (4).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (5).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (1).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (2).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (3).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (4).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
    duration: '4万時間',
  },
];
const lastestVideos = [
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen.png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (1).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (2).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (3).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (4).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (5).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (1).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (2).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (3).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (4).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (5).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (1).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (2).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (3).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
  {
    title: '旋盤のベアリング交換方法',
    img: '/videos/video_screen (4).png',
    categories: ['工作機械', '旋盤'],
    describe: '旋盤のベアリング交換を安全かつ効率的に行う手順。',
    author: '山田機械修理工房',
    date: '2024年9月10日',
  },
];
const newsData = [
  {
    icon: '/icons/icons-checked.png',
    title: '新しいパートナープログラムを開始',
    description:
      '動画投稿者向けの新しいパートナープログラムが始まりました。これにより、再生回数に応じた報酬が増加します。詳細はパートナーガイドをご覧ください。',
    date: '2024年8月20日',
  },
  {
    icon: '/icons/icons-checked.png',
    title: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ効率的に行う手順。詳細な手順については、パートナーガイドをご覧ください。',
    date: '2024年9月10日',
  },
  {
    icon: '/icons/icons-checked.png',
    title: '新しいパートナープログラムを開始',
    description:
      '動画投稿者向けの新しいパートナープログラムが始まりました。これにより、再生回数に応じた報酬が増加します。詳細はパートナーガイドをご覧ください。',
    date: '2024年8月20日',
  },
  {
    icon: '/icons/icons-checked.png',
    title: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ効率的に行う手順。詳細な手順については、パートナーガイドをご覧ください。',
    date: '2024年9月10日',
  },
  {
    icon: '/icons/icons-checked.png',
    title: '新しいパートナープログラムを開始',
    description:
      '動画投稿者向けの新しいパートナープログラムが始まりました。これにより、再生回数に応じた報酬が増加します。詳細はパートナーガイドをご覧ください。',
    date: '2024年8月20日',
  },
  {
    icon: '/icons/icons-checked.png',
    title: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ効率的に行う手順。詳細な手順については、パートナーガイドをご覧ください。',
    date: '2024年9月10日',
  },
];
const users = [
  {
    img: '/profile/1.png',
    name: '有村 架純',
    number: '112',
  },
  {
    img: '/profile/1.png',
    name: '有村 架純',
    number: '112',
  },
  {
    img: '/profile/2.png',
    name: '有村 架純',
    number: '112',
  },
  {
    img: '/profile/3.png',
    name: '有村 架純',
    number: '112',
  },
  {
    img: '/profile/4.png',
    name: '有村 架純',
    number: '112',
  },
  {
    img: '/profile/1.png',
    name: '有村 架純',
    number: '112',
  },
  {
    img: '/profile/1.png',
    name: '有村 架純',
    number: '112',
  },
  {
    img: '/profile/2.png',
    name: '有村 架純',
    number: '112',
  },
];
const chartData = {
  labels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
  datasets: [
    {
      label: '',
      data: [10, 15, 23, 12, 13, 5, 8, 15, 23, 12, 13, 5],
      borderColor: '#4291EF',
      backgroundColor: 'rgba(75, 192, 192, 0.2)',
    },
  ],
};
const videoTableRows = [
  {
    id: '1',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '2',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '3',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '4',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '5',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '6',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '7',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '8',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '9',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '10',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '11',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '12',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '13',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '14',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '15',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '16',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
  {
    id: '17',
    image: '/videos/video_screen (1).png',
    name: '旋盤のベアリング交換方法',
    description:
      '旋盤のベアリング交換を安全かつ旋盤のベアリング交換を安全かつ...',
    auth: '山田機械修理工房',
    main: '工作機械',
    sub: '旋盤',
    status: 'リクエスト中',
    date: '2024年9月10日',
  },
];
const userTableRows = [
  {
    id: '1',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: 'Admin',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '2',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '2',
    role: '有料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '3',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '無料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '4',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '無料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '5',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '',
    role: '有料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '6',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '無料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '7',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '有料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '8',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '無料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '9',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '有料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '10',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '無料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '11',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '無料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '12',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '有料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '13',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '無料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '14',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '無料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '15',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '有料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '16',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '無料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '17',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '有料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
  {
    id: '18',
    name: '有村　架純',
    avatar: '/profile/1.png',
    mail: 'guriyama@video.com',
    date: '2024年9月10日',
    count: '23',
    role: '無料会員',
    expired: '2023年9月10日 ~ 2024年9月10日',
  },
];
export {
  rows,
  users,
  slides,
  lastest,
  favorite,
  newsData,
  lastestVideos,
  favVideos,
  userIcon,
  news,
  chartData,
  videoTableRows,
  userTableRows,
};
